Repository Swift-Dev-Ninjas/swift-dev-ninjas.github.io, pull requests merged in 2018-10, with the labels that each got.

#2 Added my (Anthonys) contacts
  codeofconduct.md
Labels: hacktoberfest

#3 Update codeofconduct.md
  codeofconduct.md
Labels: bug

#1 Added Colearning-website
  .circleci/config.yml
  .dockerignore
  .gitignore
  Package.resolved
  Package.swift
  Public/.gitkeep
  Resources/Views/Layout/footer.leaf
  Resources/Views/welcome.leaf
  Sources/App/Controllers/.gitkeep
  Sources/App/Controllers/TodoController.swift
  Sources/App/Models/.gitkeep
  Sources/App/Models/Todo.swift
  Sources/App/app.swift
  Sources/App/boot.swift
  Sources/App/configure.swift
  Sources/App/routes.swift
  Sources/Run/main.swift
  Tests/.gitkeep
  Tests/AppTests/AppTests.swift
  Tests/LinuxMain.swift
  cloud.yml
Labels: enhancement, good first issue, hacktoberfest

#4 Updated the README.md file to include the getting-started-help.md file.
  CONTRIBUTING.md
  Package.resolved
  Package.swift
  Public/footer.css
  Public/images/meetup_logo.png
  Public/index.css
  Public/navigation.css
  README.md
  Resources/Views/Layout/base.leaf
  Resources/Views/Layout/footer.leaf
  Resources/Views/Layout/index.leaf
  Resources/Views/Layout/navigation.leaf
  Resources/Views/welcome.leaf
  Sources/App/Controllers/.gitkeep
  Sources/App/Controllers/TodoController.swift
  Sources/App/Models/.gitkeep
  Sources/App/Models/Todo.swift
  Sources/App/configure.swift
  Sources/App/routes.swift
  getting-started-help.md
Labels: enhancement, hacktoberfest
